# Generated by Django 5.0.6 on 2024-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album_created_date_album_is_active_album_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='duration',
            field=models.DurationField(),
        ),
    ]
